version: '3'
services:
  # The Apollo service
  apollo:
    image: mcwilliams/journey2:latest
    build:
      context: ./apollo
      dockerfile: Dockerfile
    command: sh -c "npm -g add nodemon && nodemon -v && NODE_ENV=development nodemon -V -L src/index.js"
    cpus: '0.25'
    mem_limit: 250M
    volumes:
      - ./apollo/src:/app/src:delegated
      - ./apollo/schema:/app/schema:delegated
    ports:
      - '${APOLLO_LISTEN_PORT:-8000}:${APOLLO_LISTEN_PORT:-8000}'
    environment:
      # The port for Apollo to listen to
      PORT: '${APOLLO_LISTEN_PORT:-8000}'

      # The path for the Apollo GraphQL API
      GRAPHQL_API_PATH: ${APOLLO_API_PATH:-/api/graphql}

      PRISMA_ENDPOINT: http://prisma:${PRISMA_LISTEN_PORT:-7000}
      PRISMA_SECRET: ${PRISMA_SECRET:?You must specify PRISMA_SECRET}

      
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '${PRISMA_LISTEN_PORT:-7000}:${PRISMA_LISTEN_PORT:-7000}'
    environment:
      PRISMA_CONFIG: |
      port: ${PRISMA_LISTEN_PORT:-7000}
      managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET:?You must specify PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mongo
            uri: ${MONGO_DB_CONNECTION}
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~